# Generated by Django 4.2.4 on 2023-09-20 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='img_url',
            field=models.ImageField(default='<django.db.models.fields.CharField>.jpg', upload_to='../static/images/news/%y'),
        ),
        migrations.AddField(
            model_name='news',
            name='publisher',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=200),
        ),
    ]
