# Generated by Django 4.2.4 on 2023-09-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_news_img_caption_news_img_url_news_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='../static/images/news/%y'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.CharField(default='Нөмөр', max_length=200),
        ),
    ]
