# Generated by Django 4.2.4 on 2023-09-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_news_img_url_alter_news_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='images/%y'),
        ),
    ]
