# Generated by Django 4.2.4 on 2023-09-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_alter_news_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=200)),
                ('loan_interest', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_text', models.TextField()),
                ('img_caption', models.CharField(blank=True, max_length=50, null=True)),
                ('img_url', models.ImageField(default='path_to_default_image.jpg', upload_to='images/news/%y/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
