# Generated by Django 4.2.4 on 2023-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='img_url',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='images/slide/%y/'),
        ),
    ]
