# Generated by Django 4.2.4 on 2023-09-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_title_loan_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='img_url',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='images//loan_type/%y/'),
        ),
    ]
