# Generated by Django 4.2.4 on 2023-09-21 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_loan_type_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_type',
            name='img_caption',
        ),
        migrations.RemoveField(
            model_name='loan_type',
            name='img_url',
        ),
        migrations.AddField(
            model_name='loan_type',
            name='icon',
            field=models.FileField(default='path_to_default_image.svg', upload_to='images//loan_type/%y/', validators=[django.core.validators.FileExtensionValidator('svg')]),
        ),
        migrations.AddField(
            model_name='loan_type',
            name='icon_caption',
            field=models.CharField(blank=True, default='numur', max_length=50, null=True),
        ),
    ]
