# Generated by Django 4.2.4 on 2023-09-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_loan_type_img_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='icon',
            field=models.ImageField(default='path_to_default_image.png', upload_to='images/icons/%y/'),
        ),
    ]
