# Generated by Django 4.2.4 on 2023-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
