# Generated by Django 4.2.4 on 2023-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_merchant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
