# Generated by Django 4.2.4 on 2023-09-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_merchant_merchant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_sub_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
