# Generated by Django 4.2.4 on 2023-09-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_merchant_merchant_address_merchant_merchant_sub_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_sub_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='merchant_type',
        ),
    ]
