# Generated by Django 4.2.4 on 2023-09-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_merchant_merchant_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_contract_loc',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
