# Generated by Django 4.2.4 on 2023-09-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_general_contract_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=8)),
                ('description', models.TextField(null=True)),
                ('time_table', models.CharField(max_length=200)),
                ('contract_loc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.general_contract_loc')),
            ],
        ),
    ]
