# Generated by Django 4.2.4 on 2023-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_contract_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_location',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
