# Generated by Django 4.2.4 on 2023-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_contract_location_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
