# Generated by Django 4.2.4 on 2023-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_contract_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_location',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract_location',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
