# Generated by Django 4.2.4 on 2023-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_contract_location_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_location',
            old_name='phone_number',
            new_name='phone_number1',
        ),
        migrations.AddField(
            model_name='contract_location',
            name='phone_number2',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
